### ISSUE TITLE
Internal error on command:"PID_CALIBRATE"

### ISSUE THREAD

**Issue by Michael-Bell** [Klipper3d/klipper#1043]
```
pi@octopi:~/klipper $ git rev-parse HEAD
62fc5dc2884c41eb45880b0e9c988cabb025d1c1
```
Running on a Pi3 with a genuine E3D V6 heater and thermister. I run `PID_CALIBRATE HEATER=extruder TARGET=220`, then the temperature graph will look like ![screenshot](https://i.imgur.com/e3cV7Kv.png)

I've attached my [log](https://github.com/KevinOConnor/klipper/files/2709083/PID.log).

I think this is the relevant error message:
```
Internal error on command:"PID_CALIBRATE"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 188, in process_commands
    handler(params)
  File "/home/pi/klipper/klippy/gcode.py", line 69, in <lambda>
    func = lambda params: origfunc(self.get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/pid_calibrate.py", line 39, in cmd_PID_CALIBRATE
    Kp, Ki, Kd = calibrate.calc_final_pid()
  File "/home/pi/klipper/klippy/extras/pid_calibrate.py", line 132, in calc_final_pid
    midpoint_pos = sorted(cycle_times)[len(cycle_times)/2][1]
IndexError: list index out of range
```

**Comment by muenznej** [comment]
Hi, i had such an issue with my volcano and a new thermistor. The error occurs as far as i understand because the heater verifier code throws an error if heating up takes too long.

First: check if your thermistor settings are correct ( i used a thermocouple and calibrated it ref. #1022 )
Second: The problem for me was/is:
The heater is maybe only 30 Watts and you probably have strong part cooling fans running which cause a cooling of the nozzle (especially if you are close to the print bed)  and your heater just cannot handle fast enough. I increased the tolerances for heater errors and did the PID for lower target temperature (with blowers and heat bed close). When i print i ramp the cooling over 5 layers from 0 to 100% which helps the PID to tolerate the temperature drops.

hope it makes any sense and helps :-)

**Comment by Michael-Bell** [comment]
I'm away from the printer for a few days, so I cannot test anything now, but to clarify it can heat up and maintain temps pretty well with Marlin. It would also heat quckly and run calibration at a lower temp without issue. Only when running a high temp PID test it has a curve to heating and never gets to the proper temp, only 200C usually when throwing the error. Did not seem to matter if I had it at 200 and run command or it was at ambient and running the command.

**Comment by KevinOConnor** [comment]
As mentioned above, the root cause of the above error is a "veryify_heater" check.  It looks like you will need to tune the default verify_heater settings for your extruder.

-Kevin
