### ISSUE TITLE
Ender-3 [stepper_y] "position_endstop" should be a negative number, not zero

### ISSUE THREAD

**Issue by The-Monkey-King** [Klipper3d/klipper#4780]
Affected files:
- printer-creality-ender3-v2-2020.cfg
- printer-creality-ender3-2018.cfg

Issue: 
Current configuration will cause the Y coordinates of the print area to shift lower (closer to the front of the bed) than expected. If a print uses the entire print area or at least the first 11mm of the Y-axis, the print will fail. 

Reason:
Current default of the Y axis expects the Y zero coordinate to be on the edge of the bed. 

In reality:
The Y endstop switch moves the bed away from the hotend and overhangs the edge of the bed.

 
Work:
This should be applicable to any Creality Ender-3 product, regardless of motherboard, as long as X and Y hardware endstops are still being used. Ender-3 is a bedslinger and has hardwired switch endstops for X, Y, and Z.

I am not concerning this issue with Z; I have a BLTouch wired to replace the Z switch endstop. 
The X endstop parks the hot end just on the edge of the print bed, so there is no issue there on homing.

However, when homing the Y axis, the Y endstop switch allows the bed to retract (moves the bed back from the front viewpoint) to a point where the nozzle is not in line with the edge of the bed. I propose modifying printer-creality-ender3-v2-2020.cfg and printer-creality-ender3-2018.cfg, changing the "position_endstop" from 0 to a negative number and adding "position_min" with the same negative number. You will get a boundary error if you don't add the "position_min" line.

Change:
position_endstop: 0 to **position_endstop: -10**

Add:
**position_min: -10**

[klippy.log](https://github.com/Klipper3d/klipper/files/7305569/klippy.log)

**Comment by altimmons** [comment]
I have a similar issue.

The Endstop must be between Min and Max.
but in my custom printer, the endstop might be at 0, but the Y minimum is 30.  This is because a fan will hit the z screws in the middle of the bed.

Ideally, I would set endstop position to '-30' and the y minimum to '0'

I would also settle for endstop position being 0, and y minimum as 30.
But neither of these configurations are permitted.

Further, there is no real way to circumscribe the permitted print area- which as I am sure for many people is different than the permissible movement area.

One of these configuration checks should be removed.

**Comment by Sineos** [comment]
You typically want to solve this via a combination of the `position_endstop`, `position_min` / `position_max` and the bed settings in the slicer, e.g. Prusa / Superslicer:

![grafik](https://user-images.githubusercontent.com/4459312/140622877-2810748a-28d0-4674-b13b-56650c65eefd.png)
