### ISSUE TITLE
Klipper 0.10 does not support Chinese file naming. What can you do to solve it!

### ISSUE THREAD

**Issue by pangxie0** [Klipper3d/klipper#4871]
![image](https://user-images.githubusercontent.com/93654815/140301540-1849fdec-9379-4d23-bfc1-4ee7a7edf2af.png)

**Comment by vladimir-poleh** [comment]
It seems to be a problem caused by migration to the Python3. You can try to use release version v0.10.0

To switch to this version execute these commands (assuming that Klipper install dir is `~/klipper`

```
cd ~/klipper
git checkout v0.10.0
```

Please note that this will break update mechanism. Use following command to return to the more recent version

```
git checkout master
```

**Comment by vladimir-poleh** [comment]
It seems that running Klipper on Python 3 resolves this issue.

**Comment by wlhlm** [comment]
Same issue: #4794

**Comment by Sineos** [comment]
As pointed out by @wlhlm
