### ISSUE TITLE
Transition to shutdown state: MCU 'mcu' shutdown: Rescheduled timer in the past

### ISSUE THREAD

**Issue by panik988** [Klipper3d/klipper#5031]
Hi everyone,
during a print I had a sudden shutdown of the printer.
This is the error that was generated:

Transition to shutdown state: MCU 'mcu' shutdown: Rescheduled timer in the past
This generally occurs when the micro-controller has been
requested to step at a rate higher than it is capable of
obtaining.

I tried to figure out what it was due to but without success.
What do you think could have happened?
I attach the log file.
Thank you

[klippy.log](https://github.com/Klipper3d/klipper/files/7727662/klippy.log)

**Comment by simonkuehling** [comment]
Hi @panik988,
as the error message states, this looks like the microcontroller was not able to generate the requested step frequency that was needed to follow your gcode commands.

Looking into your config, you do have quite extreme values there. I see
- 256 microsteps
- 400 steps/rotation
- 40mm movement per rotation
- maximum velocity of 1100 mm/s

which will result in ~2.8MHz of step rate **per stepper motor** at full speed if I'm not mistaken. That is likely too much for the MCU to keep up with...
Either limit your max velocity, or reduce the microstep rate in order to reduce that load.

For further configuration help, it's best to head over to the discourse forum or discord chat server! (see https://www.klipper3d.org/Contact.html)
