### ISSUE TITLE
Inaccurate endstop position when doing a delta calibrate

### ISSUE THREAD

**Issue by HCR-Mad-Bull** [Klipper3d/klipper#5046]
Hi, I've got a delta printer and when doing a delta calibration the endstops positions are always out by +0.4 which makes the nozzle too low, it says that the height is 453.6 but in reality it should be 453.2. I can manually edit the output so it's correct, but I'm unsure if the other results are also inaccurate as well which makes me worried. 

Anycubic predator
Microswitch omron magnetic probe
Skr pro 1.2
Raspberry pi 3
Latest klipper updates as of 18/12
Fluidd

Any other info you need?

**Comment by simonkuehling** [comment]
Hi @HCR-Mad-Bull, how exactly do you run the delta calibration - using the probe or manually ("paper test")?

**Comment by HCR-Mad-Bull** [comment]
Hi @simonkuehling sorry about the late reply, I was using a probe.

**Comment by simonkuehling** [comment]
Did you carefully calibrate your probe according to the [Probe Calibration](https://www.klipper3d.org/Probe_Calibrate.html) documentation?
Usually, due to mechanical flex in every system, probes trigger a bit below their actual z=0 plane, which would match your observation of the nozzle beeing too low.
