### ISSUE TITLE
How to instal for MKS GEN L or TMC2130 V1.1 and V1.0 for Core XY

### ISSUE THREAD

**Issue by KrzePikPL** [Klipper3d/klipper#512]

**Comment by AxMod3DPrint** [comment]
Installation instructions can be found at https://github.com/KevinOConnor/klipper/blob/master/docs/Installation.md 

There are example settings files in the config folder, the example-corexy.cfg should be OK. The MKS Gen L looks to be a all in one RAMPS/Mega 2560 so the standard pins should work. 

As for the TMCs the TMC section in example-extras.cfg should get you started in the correct direction.

**Comment by KrzePikPL** [comment]
no work but im no on coreXY

**Comment by AxMod3DPrint** [comment]
Please provide your log file as described in the docs/Contact.md

**Comment by KrzePikPL** [comment]
this folder is clear

**Comment by AxMod3DPrint** [comment]
I realise that English may not be your first language, as such it's difficult to put across exactly what it is you want help with. We need more info as to what exactly you have done and what the problem is, else we cannot help. If it helps, use google translate, it may not be totally accurate but it gets the idea across. 

Things that we need:
* What you have done so far
* A better description of your printer set up.
* What exactly it is you need help with

**Comment by klHaribo** [comment]
the MKS Gel L is fully compatible to the ramps1.4 board. so you can use these examples as a start
