### ISSUE TITLE
TMC2209 config error: Internal error during connect: ConfigWrapper instance has no attribute 'getlist'.

### ISSUE THREAD

**Issue by zhengyangliu** [Klipper3d/klipper#5196]
I am a newbie for klipper. But i think this method may have some problem.
When i use the tmc2209. A error was reported: 

`Internal error during connect: ConfigWrapper instance has no attribute 'getlist'`

https://github.com/Klipper3d/klipper/blob/0b918b357cb0c282d53cbdf59e1931a2054cd60a/klippy/extras/tmc_uart.py#L200.

**Comment by Sineos** [comment]
As GitHub shall mainly be used to target development relevant topics, please post your support request on https://klipper.discourse.group.

Also specifically see https://klipper.discourse.group/t/internal-error-during-connect-configwrapper-instance-has-no-attribute-getfloatlist/1780/5
Your error is most likely caused by surplus / misplaced white-space, tabs, or other "strange" characters
