### ISSUE TITLE
BL-Touch offset drift with speed

### ISSUE THREAD

**Issue by mgth** [Klipper3d/klipper#5750]
Trying to debug inconsistent bl-touch result, I got this interesting result, it seams that there is about 8ms "missing" from the returned value, while repeatability is ok at any speed, the distance measured reduce by about the distance done in 8ms at any speed.

![image](https://user-images.githubusercontent.com/2568124/188249438-32c3ef80-a7fc-49ab-887a-e285e8450220.png)
[klippy(1).zip](https://github.com/Klipper3d/klipper/files/9481596/klippy.1.zip)

**Comment by Ramalama2** [comment]
> Trying to debug inconsistent bl-touch result, I got this interesting result, it seams that there is about 8ms "missing" from the returned value, while repeatability is ok at any speed, the distance measured reduce by about the distance done in 8ms at any speed.
> 
> ![image](https://user-images.githubusercontent.com/2568124/188249438-32c3ef80-a7fc-49ab-887a-e285e8450220.png) [klippy(1).zip](https://github.com/Klipper3d/klipper/files/9481596/klippy.1.zip)

Do you have a script for that?
That's something im seeing with Microswitches either, but i was never able to convert that in a such beautiful graph.

Especially interesting is first probe either.
We know that first probe always sucks, but im wondering if that has todo with that either because the mcu somewhat sleeps or the code simply adds the delay on first probe.

**Comment by Sineos** [comment]
Surely an interesting and worthwhile discussion. And yes, the aberrant first probe is a pain but please be so kind to move this discussion to https://klipper.discourse.group
