### ISSUE TITLE
Add website link to About section on readme

### ISSUE THREAD

**Issue by aha999** [Klipper3d/klipper#5819]
It's a standard practice that a website link is to be included in the About section of the github.

Please include the website link in the About section of your project.

![image](https://user-images.githubusercontent.com/50620416/194767805-008cfd50-9a63-4d97-9bdc-625865450e82.png)

Example:

![image](https://user-images.githubusercontent.com/50620416/194767852-8edf2d85-22fe-4e8b-8018-495f2ecc0a0f.png)

**Comment by JamesH1978** [comment]
There is no actual requirement to do this, and the link to the readme shows the website clearly. not to mention that readme is the first thing you see on the code page anyway.

if this is an actual requirement please link us to documentation that states this.

I am not actually sure what the issue is here.

thanks,
James
